[project]
name = "ml"
version = "0.1.0"
description = "Machine Learning and AI service for the Claim Verifier project."
readme = "../README.md"
authors = [
    { name = "GabrielMarquezan", email = "marquezan.luz@acad.ufsm.br" }
]
requires-python = ">=3.14.7"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false